builder:
  track: dev

labels:
  app-group: estafette-ci
  type: service
  team: estafette
  language: golang

version:
  semver:
    major: 1
    minor: 0
    patch: 0
    labelTemplate: '{{branch}}-{{auto}}'
    releaseBranch: 1.0.0

stages:
  build-lint-and-package:
    parallelStages:
      build:
        image: golang:1.16-alpine
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOGC: off
        commands:
        - go test -short ./...
        - go build -a -installsuffix cgo -ldflags "-X main.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X main.app=${ESTAFETTE_GIT_NAME} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

      lint-helm-chart:
        image: extensions/helm:dev
        action: lint

      package-helm-chart:
        image: extensions/helm:dev
        action: package

  bake:
    image: extensions/docker:dev
    action: build
    repositories:
    - estafette
    path: ./publish
    copy:
    - /etc/ssl/certs/ca-certificates.crt
    - ./migrations

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        repositories:
        - estafette

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        repositories:
        - estafette

  test-migration:
    services:
    - name: cockroachdb
      image: cockroachdb/cockroach:v20.2.6
      shell: /bin/bash
      env:
        COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING: "true"
      readiness:
        path: /health?ready=1
        port: 8080
        timeoutSeconds: 120
      commands:
      - /cockroach/cockroach start-single-node --insecure --advertise-addr cockroachdb

    image: estafette/estafette-ci-db-migrator:${ESTAFETTE_BUILD_VERSION}
    env:
      COCKROACH_CONNECTION_STRING: postgresql://root@cockroachdb:26257/defaultdb?sslmode=disable
      ESTAFETTE_LOG_FORMAT: console

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - estafette
    tags:
    - ${ESTAFETTE_BUILD_VERSION_MAJOR}.${ESTAFETTE_BUILD_VERSION_MINOR}
    - ${ESTAFETTE_BUILD_VERSION_MAJOR}
    - latest

  start-kind:
    services:
    - name: kubernetes
      image: bsycorp/kind:latest-1.19
      readiness:
        path: /kubernetes-ready
        port: 10080
        timeoutSeconds: 120

  install-db:
    image: extensions/helm:dev
    action: test
    repoUrl: https://charts.cockroachdb.com/
    chart: cockroachdb
    version: 5.0.6
    release: estafette-ci-db
    values: |-
      conf:
        single-node: true
      statefulset:
        replicas: 1
      storage:
        persistentVolume:
          enabled: false
          size: 1Gi

  test-helm-chart:
    image: extensions/helm:dev
    action: test
    values: |-
      job:
        env:
        - name: COCKROACH_HOST
          value: cockroachdb-public

  clone-charts-repo:
    image: extensions/git-clone:dev
    repo: helm-charts
    branch: main

  publish-helm-chart:
    image: extensions/helm:dev
    action: publish
    repoBranch: main

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  tooling-estafette:
    stages:
      git-clone:
        image: extensions/git-clone:dev

      run-job:
        image: extensions/gke:dev
        kind: job
        namespace: estafette-ci
        container:
          repository: estafette
          env:
            COCKROACH_DATABASE: estafette.secret(dvU0YFtbQeLg03F_.eQp-XyPGfDhcN7ErIZaf83ZXsacxH7WPQC_GnQGz5Iw=.exB-VjDBJi9WBf0nDYOO_Asnu3YLMfCzrEgAGOjgj73w-NdktL7g6klqIW--t0KO6MzjReO-iKeFL8EvZQ==)
            COCKROACH_HOST: estafette.secret(55_ox0L164bPLo4D.DXZLxriEZL91JquH6Wj1DxLsFpaadLW6cL2oO6r6_YEh-PsV_mJyS5mPZA49_pCZ9Viv4TI1Eo25IMYcpvkXTGA=.CXBcxb-JK79yL-bP6mn2BR77TJbGZaeodK-5KvP8ucw7o_xZsGNuX5-LYk8jKY08cX5gD7cAsAVLttLGug==)
            COCKROACH_USER: estafette.secret(CJ9f-SH3okHZ_vR8.EtN7YKlj07HMQH_6iqNdk454Rr0UyRpo.GNNoer11kqAOSAnHbc-XVs0cfUBMGKi7IMoKsxuht6GjbE-215zO8cATQA-f8C91Ruvayh9bb620EOycQw==)
            ESTAFETTE_LOG_FORMAT: v3
          cpu:
            request: 200m
            limit: 200m
          memory:
            request: 512Mi
            limit: 512Mi
        volumemounts:
        - name: client-certs
          mountpath: /cockroach-certs
          volume:
            secret:
              secretName: estafette-ci.client.migrator
              defaultMode: 0400

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  release-helm-chart:
    stages:
      clone-charts-repo:
        image: extensions/git-clone:dev
        repo: helm-charts
        branch: main

      purge-prerelease-helm-charts:
        image: extensions/helm:dev
        action: purge
        repoBranch: main

      create-github-release:
        image: extensions/github-release:dev
