apiVersion: v1
kind: Namespace
metadata:
  name: estafette
---
apiVersion: batch/v1
kind: Job
metadata:
  name: estafette-ci-db-migrator
  namespace: estafette
  labels:
    app: estafette-ci-db-migrator
    team: tooling
spec:
  template:
    metadata:
      labels:
        app: estafette-ci-db-migrator
        team: tooling
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: In
                values:
                - "true"
      containers:
      - name: estafette-ci-db-migrator
        image: estafette/estafette-ci-db-migrator:${GO_PIPELINE_LABEL}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        env:
        - name: "COCKROACH_DATABASE"
          value: "${COCKROACH_DATABASE}"
        - name: "COCKROACH_HOST"
          value: "${COCKROACH_HOST}"
        - name: "COCKROACH_INSECURE"
          value: "${COCKROACH_INSECURE}"
        - name: "COCKROACH_CERTS_DIR"
          value: "${COCKROACH_CERTS_DIR}"
        - name: "COCKROACH_PORT"
          value: "${COCKROACH_PORT}"
        - name: "COCKROACH_USER"
          value: "${COCKROACH_USER}"
        - name: "COCKROACH_PASSWORD"
          value: "${COCKROACH_PASSWORD}"
      restartPolicy: Never